---
title: "Soil and climate model for predict admixture klass of arabidopsis"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(corrplot)
library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
source("../importance_plot.R")

# count of admixture components
adm.count = 14
all_data <- read.csv("../full_dataframes/result_k_14_climate_soil.csv")[,-1]
just.parametrs <- all_data[,-c(1:(adm.count + 3))]
```

## Random forest based on all variables

### Match admixture group for every sample base on the next simple rule, if component number N in vector > 0.7, then this sample belong to the group N.

```{r}
clear.just.parametrs <- just.parametrs

lbound <- .7
groups <- apply(all_data[, c(1:adm.count)], 1, function(current.row) {
    group <- ((current.row > lbound) * c(1:adm.count))[current.row > lbound]
    if (length(group) == 0) {
        return(NA)
    }
    return(group)
})
str(groups)
```

```{r}
clear.just.parametrs <- just.parametrs
prepared.data <- data.frame(group = groups)
prepared.data <- na.omit(cbind(prepared.data, clear.just.parametrs))
prepared.data$group <- factor(prepared.data$group)
ncol(prepared.data)
```

```{r}
set.seed(666)

train.indexes <- sample(1:nrow(prepared.data), 0.8 * nrow(prepared.data))
train <- prepared.data[train.indexes, ]
test <- prepared.data[-train.indexes, ]

res.forest <- randomForest(group ~ ., data = train)
t_pred.forest <- predict(res.forest, test)
confMat <- table(test$group, t_pred.forest)
sum(diag(confMat)) / sum(confMat)
```

```{r}
important.dot.plot(res.forest)
```






